[package]
name = "met"
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = "2.2.0"
cw-storage-plus = "2.0.0"
schemars = "0.8.21"
serde = { version = "1.0.217", features = ["std"] }

[dev-dependencies]
cosmwasm-schema = "2.2.0"
cosmwasm-vm = "2.2.0"